# Generated by Django 4.2.1 on 2023-05-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cv',
        ),
    ]
