# Generated by Django 4.2.1 on 2023-06-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0006_alter_employee_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
